This commit was manufactured by cvs2svn to create tag 'db-txn-mergepoint9-on-branch'.
git-svn-id: svn://svn.code.sf.net/p/bogofilter/code/tags/db-txn-mergepoint9-on-branch@4468 046ba1d7-8659-4f4f-8137-08d775d845e8

diff --git a/bogofilter/src/tests/printcore b/bogofilter/src/tests/printcore
--- a/bogofilter/src/tests/printcore
+++ b/bogofilter/src/tests/printcore
@@ -23,6 +23,7 @@ if [ -z "$corefile" ] ; then
     exit 0
 fi
 echo >&2 ">>> Using core file \"$corefile\"."
+trap "rm -f \"$corefile\"" 0
 
 # stage 2: pull name of executable file out of core
 backtick='`'
@@ -31,9 +32,17 @@ LC_MESSAGES=C
 export LANG LC_MESSAGES
 rm -f exit.$$
 execfile="`( $GDB -nw -batch -nx -silent -c "$corefile" </dev/null)`"
-if [ $? -gt 0 ] ; then echo >&2 "Problem with GDB program \"$GDB\"" ; exit 0; fi
+if [ $? -gt 0 ]
+then
+    echo >&2 "Problem with GDB program \"$GDB\""
+    exit 0
+fi
 execfile=`echo "$execfile" | grep -i 'ore was generated by' | cut -f2- -d$backtick | cut -f1 -d"'" | cut -f1 -d" "`
-if [ -z "$execfile" ] ; then echo >&2 "Cannot figure executable." ; exit 0; fi
+if [ -z "$execfile" ]
+then
+    echo >&2 "Cannot figure executable."
+    exit 0
+fi
 echo >&2 ">>> Using exec file \"$execfile\"."
 
 # stage 3: obtain backtrace
@@ -52,7 +61,6 @@ _EOF
 cmd="gdb -nw -r -batch -nx -x "$gdbfile" -silent "$execfile" "$corefile" </dev/null"
 echo >&2 ">>> Running command: $cmd"
 eval "$cmd"
-if [ $? -eq 0 ] ; then rm -f "$corefile" ; fi
 rm -f "$gdbfile"
 echo >&2 ">>> Done."
 exit 0
