Search for nsgmls.
git-svn-id: svn://svn.code.sf.net/p/bogofilter/code/trunk/bogofilter@3723 046ba1d7-8659-4f4f-8137-08d775d845e8

diff --git a/doc/Makefile.am b/doc/Makefile.am
--- a/doc/Makefile.am
+++ b/doc/Makefile.am
@@ -3,6 +3,11 @@
 # Tell BSD make(1) to not remake the .1in and .htmlin files.
 SUFFIXES= .1 .1in .htmlin .html
 
+# requires:
+#   xmllint (libxml2)
+#   xmlto (cyberelk.net)
+#   nsgmls (opensp)
+
 # what to build
 man_MANS = bogofilter.1 bogoutil.1 bogoupgrade.1 bogolexer.1 bogotune.1
 
@@ -12,6 +17,8 @@ all: $(man_MANS) $(html_MANS)
 
 CLEANFILES = $(man_MANS) $(html_MANS)
 
+HTML_DOCS = bogofilter-faq.html bogofilter-faq-fr.html
+
 # what to distribute
 EXTRA_DIST = \
 	     bogofilter.xml bogofilter.1in bogofilter.htmlin \
@@ -19,7 +26,7 @@ EXTRA_DIST = \
 	     bogotune.xml bogotune.1in bogotune.htmlin \
 	     bogoupgrade.xml bogoupgrade.1in bogoupgrade.htmlin \
 	     bogoutil.xml bogoutil.1in bogoutil.htmlin \
-	     bogofilter-faq.html \
+	     $(HTML_DOCS) \
 	     bogofilter-tuning.HOWTO \
 	     bogofilter-SA-2002-01 \
 	     integrating-with-postfix \
@@ -45,21 +52,27 @@ EXTRA_DIST = \
 	|| { rm -f $@ ; exit 1 ; }
 
 if ENABLE_XMLTO
+check-local:
+	@( set -e ; for i in $(HTML_DOCS) ; do $(NSGMLS) -s $$i \
+	    || { echo >&2 "ERROR: $$i does not validate." ; exit 1 ; } ; done )
+
 # Use Perl to fix up br0ken 0xa0 characters that the XML DocBook style
 # sheets emit instead of "\ " for roff or "&nbsp;" for HTML,
 # respectively.
 .xml.htmlin:
+	xmllint --noout --postvalid $<
 	if test -f $(srcdir)/$@ && test $(srcdir)/$@ -nt $< ; then \
 	    cp $(srcdir)/$@ . ; else \
-	if xmlto html-nochunks $< ; then f=$@ ; mv $${f%%in} $@ ; else rm -f $@ ; exit 1 ; fi ; \
-	perl -pl -e "s|\xA0|&nbsp;|g" -i $@ || rm -f $@ ; \
+	  if xmlto html-nochunks $< ; then f=$@ ; mv $${f%%in} $@ ; else rm -f $@ ; exit 1 ; fi ; \
+	  perl -pl -e "s|\xA0|&nbsp;|g" -i $@ || { rm -f $@ ; exit 1 ; }\
 	fi
 
 .xml.1in:
+	xmllint --noout --postvalid $<
 	if test -f $(srcdir)/$@ && test $(srcdir)/$@ -nt $< ; then \
 	    cp $(srcdir)/$@ . ; else \
 	if xmlto man $< ; then f=$@ ; mv $${f%in} $@ ; else rm -f $@ ; exit 1 ; fi ; \
-	perl -pl -e "s|\xA0|\\ |g" -i $@ || rm -f $@ ; \
+	perl -pl -e "s|\xA0|\\ |g" -i $@ || { rm -f $@ ; exit 1 ; }\
 	fi
 else
 .xml.1in:
