If no catalog file present, print warning and skip validation.
git-svn-id: svn://svn.code.sf.net/p/bogofilter/code/trunk@3772 046ba1d7-8659-4f4f-8137-08d775d845e8

diff --git a/bogofilter/doc/Makefile.am b/bogofilter/doc/Makefile.am
--- a/bogofilter/doc/Makefile.am
+++ b/bogofilter/doc/Makefile.am
@@ -53,9 +53,12 @@ EXTRA_DIST = \
 
 if ENABLE_XMLTO
 dist-hook:
-	@case "$(MFLAGS)" in *s*) : ;; *) echo >&2 "validating $(HTML_DOCS)" ;; esac
-	@( set -e ; for i in $(HTML_DOCS) ; do $(NSGMLS) -s $(srcdir)/$$i \
-	    || { echo >&2 "ERROR: $$i does not validate." ; exit 1 ; } ; done )
+	@if [ ! -f catalog ] ; then \
+	echo ; echo "Warning: 'catalog' file not present; see 'README.validation'". ; echo ; else \
+	case "$(MFLAGS)" in *s*) : ;; *) echo >&2 "validating $(HTML_DOCS)" ;; esac ; \
+	( set -e ; for i in $(HTML_DOCS) ; do $(NSGMLS) -s $(srcdir)/$$i \
+	    || { echo >&2 "ERROR: $$i does not validate." ; exit 1 ; } ; done ) ; \
+	fi
 
 # Use Perl to fix up br0ken 0xa0 characters that the XML DocBook style
 # sheets emit instead of "\ " for roff or "&nbsp;" for HTML,
