Improved configure script for locking functions, and improved the error messag when the configure script can't find a suitable BerkeleyDB version installed.
git-svn-id: svn://svn.code.sf.net/p/bogofilter/code/trunk@27 046ba1d7-8659-4f4f-8137-08d775d845e8

diff --git a/bogofilter/configure b/bogofilter/configure
--- a/bogofilter/configure
+++ b/bogofilter/configure
@@ -2804,10 +2804,6 @@ fi
 
 
 
-
-
-
-
 # Check whether --with-judy or --without-judy was given.
 if test "${with_judy+set}" = set; then
   withval="$with_judy"
@@ -3201,8 +3197,8 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 _ACEOF
 
 else
-  { { echo "$as_me:$LINENO: error: Can not locate a suitable BerkeleyDB db.h header file. Use --with-db=PATH to specify the path to a v3+ install directory" >&5
-echo "$as_me: error: Can not locate a suitable BerkeleyDB db.h header file. Use --with-db=PATH to specify the path to a v3+ install directory" >&2;}
+  { { echo "$as_me:$LINENO: error: Can not locate a suitable BerkeleyDB db.h header file. Use --with-db=PATH to specify the path to a v3+ install directory. You can download BerkeleyDB 4.x from http://www.sleepycat.com" >&5
+echo "$as_me: error: Can not locate a suitable BerkeleyDB db.h header file. Use --with-db=PATH to specify the path to a v3+ install directory. You can download BerkeleyDB 4.x from http://www.sleepycat.com" >&2;}
    { (exit 1); exit 1; }; }
 
 fi
@@ -4322,36 +4318,6 @@ fi
 
 done
 
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
-#include <sys/file.h>
-
-_ACEOF
-if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
-  egrep "lockf" >/dev/null 2>&1; then
-  cat >>confdefs.h <<\_ACEOF
-#define HAVE_LOCKF 1
-_ACEOF
-
-fi
-rm -f conftest*
-
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
-#include <sys/file.h>
-
-_ACEOF
-if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
-  egrep "flock" >/dev/null 2>&1; then
-  cat >>confdefs.h <<\_ACEOF
-#define HAVE_FLOCK 1
-_ACEOF
-
-fi
-rm -f conftest*
-
 
 for ac_header in syslog.h
 do
@@ -5203,7 +5169,10 @@ fi
 
 
 
-for ac_func in alarm bzero ftruncate memset mkdir socket strdup strerror
+
+
+
+for ac_func in alarm bzero ftruncate memset mkdir socket strdup strerror flock lockf fcntl
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $ac_func" >&5
